version: '3'
services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always
#networks:
#  default:
#    external:
#      name: ....
